In [6]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [7]:
import numpy as np

In [8]:
np.__version__

'1.19.5'

vector or 1D Array

In [9]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2D array

In [10]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[0]

1

In [12]:
a[2:5]

array([3, 4, 5])

In [13]:
L=[1,2,3,4,5,6,7,8,9,10]
L[2:5]

[3, 4, 5]

In [14]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [15]:
L[:6]

[1, 2, 3, 4, 5, 6]

In [16]:
a[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [17]:
L[3:]

[4, 5, 6, 7, 8, 9, 10]

In [18]:
a[-1]

10

In [19]:
a[-2]

9

In [20]:
L[-2]

9

In [21]:
a[2:-3]

array([3, 4, 5, 6, 7])

In [22]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [23]:
a[-5:-1]

array([6, 7, 8, 9])

In [24]:
np.size(a)

10

In [25]:
np.shape(a)

(10,)

In [26]:
a[a[2]]

4

In [27]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [28]:
a = a.reshape(1,10)
np.shape(a)

(1, 10)

In [29]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
a[0,0]

1

In [31]:
L = [[1,2,3],[4,5,6],[7,8,9]]

In [32]:
L[0][0]

1

In [33]:
a[1,:]

array([4, 5, 6])

In [34]:
a[:,2]

array([3, 6, 9])

In [35]:
a[:,0]=1
a

array([[1, 2, 3],
       [1, 5, 6],
       [1, 8, 9]])

In [36]:
a[1,:]=0
a

array([[1, 2, 3],
       [0, 0, 0],
       [1, 8, 9]])

In [37]:
a[0:2,:] = 8
a

array([[8, 8, 8],
       [8, 8, 8],
       [1, 8, 9]])

In [38]:
a.shape

(3, 3)

In [39]:
np.size(a,1)

3

In [40]:
np.size(a,0)

3

In [41]:
a.ndim

2

In [42]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [43]:
np.array(np_mix_matrix[:,1], dtype = int)

array([2, 4, 6])

In [44]:
a = np.zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [45]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [46]:
c = np.full((2,2),8)
c

array([[8, 8],
       [8, 8]])

In [47]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [48]:
c*d

array([[8., 0.],
       [0., 8.]])

In [49]:
np.matmul(c,d)

array([[8., 8.],
       [8., 8.]])

In [50]:
2*np.ones((2,2))

array([[2., 2.],
       [2., 2.]])

In [51]:
np.sqrt(np.full((2,2),9))

array([[3., 3.],
       [3., 3.]])

In [52]:
np.empty([5,5])

array([[4.63590532e-310, 0.00000000e+000, 3.68321948e+180,
        1.33528187e+160, 1.67501661e+243],
       [2.86749934e+161, 2.06935133e+243, 6.21744767e-311,
        6.59046452e-244, 3.06528923e-313],
       [1.02605457e-307, 1.33360316e+241, 3.28357629e-310,
        1.23695058e+012, 1.51606652e-312],
       [2.28700218e-308, 1.33360297e+241, 1.54628975e+218,
        2.53710363e-308, 5.07588417e-116],
       [7.44044317e-251, 5.41559547e-240, 7.21523165e-240,
        2.16840741e+243, 9.48606040e-321]])

In [53]:
np.random.rand()

0.9279125358173779

In [54]:
np.random.randint(10)

4

In [55]:
[np.round(np.random.rand()*10) for item in range(10)]

[10.0, 5.0, 2.0, 3.0, 3.0, 9.0, 0.0, 9.0, 8.0, 10.0]

In [56]:

[np.round(np.random.randint(5))for item in range(10)]

[4, 1, 1, 4, 2, 2, 4, 1, 3, 2]

In [57]:
np.random.seed(1)
np.random.randint(0,6)

5

In [58]:
np.random.rand(5,5)

array([[0.99718481, 0.93255736, 0.12812445, 0.99904052, 0.23608898],
       [0.39658073, 0.38791074, 0.66974604, 0.93553907, 0.84631092],
       [0.31327352, 0.52454816, 0.44345289, 0.22957721, 0.53441391],
       [0.91396202, 0.45720481, 0.43069857, 0.93912779, 0.77838924],
       [0.71597052, 0.8027575 , 0.09280081, 0.51815255, 0.86502025]])

In [59]:
np.random.seed(1)
np.random.randint(2,5)

3

In [60]:
np.round(np.random.rand(5,5))

array([[1., 1., 0., 1., 0.],
       [0., 0., 1., 1., 1.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 1.],
       [1., 1., 0., 1., 1.]])

In [61]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([ 2,  9,  9,  4, 10])

In [62]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False)

array([10,  3,  1,  5,  2])

In [63]:
np_matrix = np.random.rand(5,5)
idx_choose = np.random.choice(5,3)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0.31551563, 0.68650093, 0.83462567, 0.01828828, 0.75014431],
       [0.98886109, 0.74816565, 0.28044399, 0.78927933, 0.10322601],
       [0.98886109, 0.74816565, 0.28044399, 0.78927933, 0.10322601]])

ข้อ 1


In [64]:
np_matrix = np.random.rand(5,5)
idx_choose = np.random.choice(5,10)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose[:,-1]= np.round(np_matrix_choose[:,-1])
np_matrix_choose

array([[0.49305959, 0.54060051, 0.7654851 , 0.04534573, 0.        ],
       [0.89213587, 0.37758434, 0.53842469, 0.65229888, 0.        ],
       [0.57100856, 0.63783648, 0.12631489, 0.69020459, 1.        ],
       [0.79240359, 0.02980136, 0.88312548, 0.54078819, 0.        ],
       [0.89213587, 0.37758434, 0.53842469, 0.65229888, 0.        ],
       [0.35393909, 0.76323305, 0.35653172, 0.75278835, 1.        ],
       [0.35393909, 0.76323305, 0.35653172, 0.75278835, 1.        ],
       [0.89213587, 0.37758434, 0.53842469, 0.65229888, 0.        ],
       [0.89213587, 0.37758434, 0.53842469, 0.65229888, 0.        ],
       [0.49305959, 0.54060051, 0.7654851 , 0.04534573, 0.        ]])

In [65]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 9,  2,  6,  6,  2],
       [ 7,  7,  0,  6,  5],
       [ 1, 10,  4,  6,  0],
       [ 6,  5,  1,  2,  1],
       [ 5,  4, 10,  0,  7]])

In [66]:
rng = np.random.RandomState(0)
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[1, 0, 1, 1, 0],
       [1, 1, 1, 2, 1],
       [0, 0, 2, 1, 0],
       [0, 1, 2, 1, 1],
       [0, 1, 0, 1, 0]])

In [67]:
i,j = np.where(np_matrix == 2)

In [68]:
i

array([1, 2, 3])

In [69]:
j

array([3, 2, 2])

In [70]:
i,j = np.where(np_matrix==2)
[(i[ii],j[ii])for ii in range (len(i))]

[(1, 3), (2, 2), (3, 2)]

ข้อสอง

In [71]:
idx = [1,2,3,4,5]
np_matrix[len(idx)-1,:]

array([0, 1, 0, 1, 0])

In [72]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

array([[1, 0, 1, 1, 0],
       [0, 1, 2, 1, 1],
       [0, 1, 0, 1, 0]])

In [73]:
np_matrix = np.random.randint(10,size = (5,5))
np_matrix

array([[1, 1, 8, 7, 0],
       [3, 4, 2, 0, 3],
       [5, 1, 2, 4, 3],
       [0, 6, 0, 7, 2],
       [8, 3, 0, 8, 4]])

In [74]:
a = (np_matrix == 2)
a

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [75]:
 np_matrix[a] = 99
np_matrix

array([[ 1,  1,  8,  7,  0],
       [ 3,  4, 99,  0,  3],
       [ 5,  1, 99,  4,  3],
       [ 0,  6,  0,  7, 99],
       [ 8,  3,  0,  8,  4]])

ข้อสี่

In [76]:
random_matrix = np.random.randint(10, size = (10,5))
random_matrix

array([[2, 9, 0, 3, 8],
       [1, 4, 3, 3, 6],
       [7, 3, 5, 3, 2],
       [4, 4, 0, 3, 3],
       [8, 3, 5, 6, 7],
       [5, 1, 7, 0, 2],
       [8, 2, 1, 4, 0],
       [4, 1, 7, 3, 1],
       [6, 6, 9, 6, 9],
       [6, 0, 0, 2, 9]])

In [77]:
group = np.random.randint(2, size = 10)
group

array([0, 0, 0, 1, 0, 1, 1, 0, 0, 1])

In [80]:
random_matrix[np.where(group == 1)]

array([[4, 4, 0, 3, 3],
       [5, 1, 7, 0, 2],
       [8, 2, 1, 4, 0],
       [6, 0, 0, 2, 9]])

In [81]:
random_matrix[np.where(group == 0 )]

array([[2, 9, 0, 3, 8],
       [1, 4, 3, 3, 6],
       [7, 3, 5, 3, 2],
       [8, 3, 5, 6, 7],
       [4, 1, 7, 3, 1],
       [6, 6, 9, 6, 9]])